version: "3.7"
services:
  minesweeper-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/go/src/minesweeper-api
    links:
      - dbpostgres
    environment:
      - SCOPE=local
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    ports:
      - "8080:8080"
  
  dbpostgres:
    build:
      context: .
      dockerfile: pg.Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "5432:5432"