// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	errors "minesweeper-api/errors"

	mock "github.com/stretchr/testify/mock"

	models "minesweeper-api/models"
)

// GamesService is an autogenerated mock type for the GamesService type
type GamesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: settings
func (_m *GamesService) Create(settings *models.Settings) (*models.Game, *errors.ApiError) {
	ret := _m.Called(settings)

	var r0 *models.Game
	if rf, ok := ret.Get(0).(func(*models.Settings) *models.Game); ok {
		r0 = rf(settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}

	var r1 *errors.ApiError
	if rf, ok := ret.Get(1).(func(*models.Settings) *errors.ApiError); ok {
		r1 = rf(settings)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.ApiError)
		}
	}

	return r0, r1
}
